# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: InsideAutism
  de: InsideAutism
language:
  en: English
  de: Deutsch
email: max06.net@gmail.com
description:
  en: Autism inside - how to work with autistic people
  de: Autism inside - wie man mit Autisten zusammen arbeitet
index:
  en:
  de: de/home/
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://insideAutism.github.io" # the base hostname & protocol for your site
github_username:  InsideAutism
github_repository: InsideAutism.github.io
twitter_username: max06de

# Build settings
markdown: kramdown

remote_theme: pmarsceill/just-no-docs

defaults:
  - scope:
      type: "pages"
    values:
      header: false
